# Generated by Django 3.1.6 on 2021-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='timeTaken',
            field=models.IntegerField(),
        ),
    ]
