# Generated by Django 3.1.6 on 2021-02-27 12:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/userPost/')),
                ('slug', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField()),
                ('dateUpdates', models.IntegerField()),
                ('timeRead', models.CharField(max_length=10)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('userStatus', models.CharField(max_length=50)),
                ('adminStatus', models.BooleanField(default=False)),
                ('authorUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
