# Generated by Django 3.1.6 on 2021-03-04 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=50)),
                ('Dob', models.DateField(blank=True, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('District', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('coverImage', models.ImageField(blank=True, default='defaultCover.jpg', null=True, upload_to='images/coverImage/')),
                ('profileImage', models.ImageField(blank=True, default='defaultProfile.jpg', null=True, upload_to='images/profileImage/')),
                ('isPublic', models.BooleanField(default=False)),
                ('securityQues', models.CharField(blank=True, max_length=200, null=True)),
                ('securityAns', models.CharField(blank=True, max_length=400, null=True)),
                ('language', models.CharField(blank=True, max_length=400, null=True)),
                ('UserUsername', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
