# Generated by Django 3.1.6 on 2021-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguage',
            name='quesCount',
            field=models.IntegerField(default=0),
        ),
    ]
