# Generated by Django 3.1.6 on 2021-03-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_userlanguage_quescount'),
    ]

    operations = [
        migrations.CreateModel(
            name='userQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ques', models.CharField(max_length=200)),
                ('choice1', models.CharField(max_length=200)),
                ('choice2', models.CharField(max_length=200)),
                ('choice3', models.CharField(max_length=200)),
                ('choice4', models.CharField(max_length=200)),
                ('Ans', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userLang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.userlanguage')),
            ],
        ),
    ]
