# Generated by Django 3.1.6 on 2021-03-18 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0003_userques'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSnippetLanguage',
            fields=[
                ('language', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('snippetCount', models.IntegerField(default=0)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
