# Generated by Django 3.1.6 on 2021-03-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0004_usersnippetlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSnip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userLang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.usersnippetlanguage')),
            ],
        ),
    ]
