# Generated by Django 3.1.6 on 2021-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0005_usersnip'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersnip',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
